## 원근 변환

In [1]:
import cv2
import numpy as np
import math

In [2]:
img = cv2.imread('./dataset/card1.jpg')

In [3]:
width, height = 220, 180
pts1 = np.float32([[282,252],[496,75],[547,581],[760,410]])

width = math.pow(pts1[1][0]-pts1[0][0],2) + math.pow(pts1[1][1]-pts1[0][1],2)
width = int(math.sqrt(width))
height = math.pow(pts1[2][0]-pts1[0][0],2) + math.pow(pts1[2][1]-pts1[0][1],2)
height = int(math.sqrt(height))
# print(width)
# print(height)
pts2 = np.float32([[0,0],[width,0],[0,height],[width,height]])

matrix = cv2.getPerspectiveTransform(pts1,pts2)
output = cv2.warpPerspective(img.copy(), matrix, (width, height))

# print(pts1)
for x in range(4):
    cv2.circle(img, (pts1[x][0],pts1[x][1]), 5, (0,0,255), cv2.FILLED)


<ipython-input-3-48c6ee01c8ed>:17: DeprecationWarning: an integer is required (got type numpy.float32).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  cv2.circle(img, (pts1[x][0],pts1[x][1]), 5, (0,0,255), cv2.FILLED)


In [4]:
print(matrix)

[[ 7.74834750e-01 -6.24107018e-01 -6.12284311e+01]
 [ 6.18838207e-01  7.48199866e-01 -3.63058741e+02]
 [ 2.42440714e-06 -5.06144609e-05  1.00000000e+00]]


In [5]:
cv2.imshow('Original Image', img)
cv2.imshow('Output Image', output)
cv2.waitKey(0)

113

In [ ]:
# 가로, 세로
# 282, 252
# 496, 75
# 547, 581
# 760, 410